on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest', 'macos-latest', 'ubuntu-latest']
        perl: [ '5.30', '5.28' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iqn DBD::SQLite File::Basename File::Spec File::pfopen
          cpanm -iqn File::Temp Error::Simple Carp B::Lint warnings::unused
      - name: Run Tests
        run: |
          perl -c -Ilib lib/NJH/Snippets/DB.pm
          perl -c -Ilib -MO=Lint lib/NJH/Snippets/DB.pm
          perl -c -Ilib -Mwarnings::unused lib/NJH/Snippets/DB.pm
